export const FIREBASE_GET_IMAGE_REFS = 'FIREBASE_GET_IMAGE_REFS';
export const FIREBASE_GET_CONCERTS = 'FIREBASE_GET_CONCERTS';
export const FIREBASE_GET_ABOUT_US = 'FIREBASE_GET_ABOUT_US';
export const FIREBASE_GET_WELCOME_BG = 'FIREBASE_GET_WELCOME_BG';
export const FIREBASE_GET_SHOP = 'FIREBASE_GET_SHOP';
export const SEND_ORDER_REQUEST_MAIL = 'SEND_ORDER_REQUEST_MAIL';
